deployment:
  name: react-app
  container:
    image:
      repository:
      tag: latest
    imagePullPolicy: Always
    resources:
      requests:
        cpu: 250m
        memory: 1Gi
    containerPort: 5000
  replicas: 4

service:
  name: react-app
  type: ClusterIP
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000

ingress:
  name: react-app
  port: 5000
  dnsHostname:
  annotations: {}
