---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: aws-efs-csi-driver
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://kubernetes-sigs.github.io/aws-efs-csi-driver/
