---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: istio
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: istio
spec:
  interval: 5m0s
  url: https://istio-release.storage.googleapis.com/charts
