---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 5m0s
  url: https://kubernetes-sigs.github.io/metrics-server
