---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: flux-system
spec:
  chart:
    spec:
      chart: aws-load-balancer-controller
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: eks-charts
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    serviceAccount:
      create: true
      name: SA_ALB_NAME
      annotations:
        eks.amazonaws.com/role-arn: SA_ALB_IAM_ROLE_ARN
    region: AWS_REGION
    clusterName: EKS_CLUSTER_NAME
  interval: 2m0s
  releaseName: aws-load-balancer-controller
  targetNamespace: kube-system
