---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  chart:
    spec:
      chart: external-dns
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    serviceAccount:
      create: false
      name: SA_EXTERNAL_DNS_NAME
    region: AWS_REGION
    clusterName: EKS_CLUSTER_NAME
    domainFilters: ["EXTERNAL_DNS_DOMAIN_FILTER"]
  interval: 2m0s
  releaseName: external-dns
  targetNamespace: kube-system
