---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: react-app
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./charts/react-app
      version: ">=0.1.0"
      sourceRef:
        kind: GitRepository
        name: react-app
        namespace: flux-system
  values:
    container:
      image:
        repository: ECR_REPO
        tag: latest
    ingress:
      annotations:
        alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":
          { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
        alb.ingress.kubernetes.io/certificate-arn: "AWS_ACM_REACT_APP_ARN"
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/ssl-redirect: "443"
        alb.ingress.kubernetes.io/target-type: ip
        external-dns.alpha.kubernetes.io/hostname: AWS_REACT_APP_DOMAIN_NAME
      dnsHostname:
  interval: 10m0s
  releaseName: react-app
  targetNamespace: react-app
