---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
 name: aws-sqs-queue-scaledobject
 namespace: sqs-app
spec:
  minReplicaCount: 0
  maxReplicaCount: 100
  pollingInterval: 15
  cooldownPeriod:  30
  scaleTargetRef:
    name: sqs-consumer
  triggers:
  - type: aws-sqs-queue
    authenticationRef:
      name: keda-trigger-auth-aws-credentials
    metadata:
      queueURL: https://sqs.us-west-2.amazonaws.com/704855531002/eks-fluxcd-lab-sqs-queue
      queueLength: "5"
      awsRegion: "us-west-2"
      identityOwner: operator
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-aws-credentials
  namespace: sqs-app
spec:
  podIdentity:
    provider: aws-eks
