apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.react-app.name | quote }}
  labels:
    app: react-app
  {{- include "react-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.react-app.replicas }}
  selector:
    matchLabels:
      app: react-app
    {{- include "react-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: react-app
      {{- include "react-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        envFrom:
        - configMapRef:
            name: {{ .Values.configMap.name | quote }}
        - secretRef:
            name: {{ .Values.secret.name | quote }}
        image: {{ .Values.react-app.container.image.repository }}:{{ .Values.react-app.container.image.tag }}
        imagePullPolicy: {{ .Values.react-app.container.imagePullPolicy }}
        name: react-app
        ports:
        - containerPort: {{ .Values.react-app.container.containerPort }}
          protocol: TCP
        resources: {{- toYaml .Values.react-app.container.resources | nindent 10 }}
