---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-efs-csi-driver
  namespace: flux-system
spec:
  chart:
    spec:
      chart: aws-efs-csi-driver
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: aws-efs-csi-driver
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    controller:
      serviceAccount:
        create: false
        name: sa-aws-efs-csi
  interval: 2m0s
  releaseName: aws-efs-csi-driver
  targetNamespace: kube-system
