---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-ebs-csi-driver
  namespace: flux-system
spec:
  chart:
    spec:
      chart: aws-ebs-csi-driver
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: aws-ebs-csi-driver
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    controller:
      serviceAccount:
        create: false
        name: sa-aws-ebs-csi
    node:
      serviceAccount:
        create: false
        name: sa-aws-ebs-csi
    region: us-west-2
    clusterName: eks-fluxcd-lab
  interval: 2m0s
  releaseName: aws-ebs-csi-driver
  targetNamespace: kube-system
