---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cluster-autoscaler
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cluster-autoscaler
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cluster-autoscaler
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    autoDiscovery:
      clusterName: eks-fluxcd-lab
    awsRegion: us-west-2
    cloudProvider: aws
    rbac:
      serviceAccount:
        create: true
        name: cluster-autoscaler
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::704855531002:role/eks-fluxcd-lab-cluster-autoscaler
    replicaCount: 2
  interval: 2m0s
  releaseName: cluster-autoscaler
  targetNamespace: kube-system
