apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: istio-base
      namespace: flux-system
    - name: istiod
      namespace: flux-system
  chart:
    spec:
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 1m
  targetNamespace: istio-ingress
