apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: istio
spec:
  interval: 5m
  releaseName: istio-gateway
  dependsOn:
    - name: istio-base
      namespace: flux-system
    - name: istiod
      namespace: flux-system
  chart:
    spec:
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 1m
  values:
    # name: istio-ingressgateway
    service:
      type: NodePort
  targetNamespace: istio-ingress
