apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingressgateway
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: istio
spec:
  dependsOn:
    - name: istio-base
      namespace: flux-system
    - name: istiod
      namespace: flux-system
  chart:
    spec:
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  values:
    # name: istio-ingressgateway
    service:
      type: NodePort
      ports:
      - name: status-port
        appProtocol: http
        port: 15021
        protocol: TCP
        targetPort: 15021
      - name: http2
        appProtocol: http2
        port: 80
        protocol: TCP
        targetPort: 80
      - name: https
        appProtocol: https
        port: 443
        protocol: TCP
        targetPort: 443
    autoscaling:
      minReplicas: 2
  interval: 2m0s
  targetNamespace: istio-ingress
  releaseName: istio-gateway
