apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: istio
spec:
  dependsOn:
    - name: istio-base
      namespace: flux-system
  chart:
    spec:
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio
      interval: 2m0s
  values:
    pilot:
      autoscaleMin: 2
  interval: 2m0s
  releaseName: istiod
  targetNamespace: istio-system
