apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: keda
spec:
  chart:
    spec:
      chart: keda
      sourceRef:
        kind: HelmRepository
        name: keda
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    serviceAccount:
      create: true
      annotations:
        eks.amazonaws.com/role-arn: sa-external-dnsarn:aws:iam::704855531002:role/sa-eks-fluxcd-lab-sqs-keda
  interval: 2m0s
  releaseName: keda
  targetNamespace: keda
