---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bookinfo
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./charts/bookinfo
      version: ">=1.0.0"
      sourceRef:
        kind: GitRepository
        name: aws-eks-fluxcd-lab
        namespace: flux-system
  interval: 2m0s
  releaseName: bookinfo
  targetNamespace: bookinfo
