---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kiali-operator
      # version: ">=6.0.0"
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: flux-system
  values:
    # resources:
    #   requests:
    #     cpu: 100m
    #     memory: 128Mi
    #   limits:
    #     memory: 512Mi
    # replicaCount: 6
    cr:
      create: true
      namespace: istio-system
      spec:
        external_services:
          prometheus:
            # Prometheus service name is "metrics" and is in the "telemetry" namespace
            url: "http://kube-prometheus-stack-prometheus.monitoring.svc:9090/"
          grafana:
            auth:
              # ca_file: ""
              # insecure_skip_verify: false
              password: "kiali"
              # token: ""
              type: "none"
              # use_kiali_token: false
              username: "kiali"
            enabled: true
            in_cluster_url: 'http://kube-prometheus-stack-grafana.monitoring.svc/'
            url: 'https://grafana.dallin.brewsentry.com'
            dashboards:
            - name: "Istio Service Dashboard"
            - name: "Istio Workload Dashboard"
            - name: "Istio Mesh Dashboard"
            - name: "Istio Control Plane Dashboard"
            - name: "Istio Performance Dashboard"
            - name: "Istio Wasm Extension Dashboard"
          istio:
            component_status:
              components:
              - app_label: "istiod"
                is_core: true
                is_proxy: false
              - app_label: "gateway"
                is_core: true
                is_proxy: true
                namespace: "istio-ingress"
              enabled: true

  interval: 2m0s
  releaseName: kiali
  targetNamespace: kiali-operator
