---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-backend
  namespace: flux-system
spec:
  chart:
    spec:
      chart: podinfo
      version: ">=6.5.0"
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
  values:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 512Mi
    cache: tcp://podinfo-redis:6379
    hpa:
      enabled: true
      maxReplicas: 10
      cpu: 80
    replicaCount: 2
    service:
      grpcService: backend
    serviceMonitor:
      enabled: true
  interval: 2m0s
  releaseName: podinfo-backend
  targetNamespace: podinfo
