---
apiVersion: v1
data:
  redis.conf: |
    maxmemory 64mb
    maxmemory-policy allkeys-lru
    save ""
    appendonly no
kind: ConfigMap
metadata:
  labels:
    app: podinfo-redis
  name: redis-config
  namespace: podinfo
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: podinfo-redis
  name: podinfo-redis
  namespace: podinfo
spec:
  ports:
  - name: tcp
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: podinfo-redis
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    env: dev
    instance: webapp
  name: podinfo-redis
  namespace: podinfo
spec:
  selector:
    matchLabels:
      app: podinfo-redis
  template:
    metadata:
      labels:
        app: podinfo-redis
    spec:
      containers:
      - command:
        - redis-server
        - /redis-master/redis.conf
        image: redis:7.0.7
        imagePullPolicy: IfNotPresent
        livenessProbe:
          initialDelaySeconds: 5
          tcpSocket:
            port: redis
          timeoutSeconds: 5
        name: redis
        ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 1000m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 32Mi
        volumeMounts:
        - mountPath: /var/lib/redis
          name: data
        - mountPath: /redis-master
          name: config
      volumes:
      - emptyDir: {}
        name: data
      - configMap:
          items:
          - key: redis.conf
            path: redis.conf
          name: redis-config
        name: config
