---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: react-app
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./charts/react-app
      version: ">=1.0.0"
      sourceRef:
        kind: GitRepository
        name: react-app
        namespace: flux-system
  values:
    deployment:
      container:
        image:
          repository: 704855531002.dkr.ecr.us-west-2.amazonaws.com/eks-fluxcd-lab-react-app
          tag: latest
    ingress:
      annotations:
        alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":
          { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
        alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-west-2:704855531002:certificate/9f9e0f3e-73a0-4559-ba5c-870db7810871"
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/ssl-redirect: "443"
        alb.ingress.kubernetes.io/target-type: ip
        external-dns.alpha.kubernetes.io/hostname: react-app.dallin.brewsentry.com
      dnsHostname: react-app.dallin.brewsentry.com
  interval: 2m0s
  releaseName: react-app
  targetNamespace: react-app
