---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
  annotations:
    metadata.weave.works/description: This is the Weave GitOps Dashboard. It provides
      a simple way to get insights into your GitOps workloads.
spec:
  chart:
    spec:
      chart: weave-gitops
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: flux-system
      # interval: 12h
  values:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 1
        memory: 512Mi
    replicaCount: 1
    adminUser:
      create: true
      username: admin
      passwordHash: $2a$10$z6BEJcTqCTgxlYr3YLOwo.TO4PhKPHagHWNVDItGwfyuJa/2EfM3K
    # ingress:
    #   enabled: true
    #   className: "alb"
    #   annotations:
    #     alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":
    #       { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    #     alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-west-2:704855531002:certificate/005ac9c4-7519-46c3-83e1-131829348755"
    #     alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    #     alb.ingress.kubernetes.io/scheme: internet-facing
    #     alb.ingress.kubernetes.io/ssl-redirect: "443"
    #     alb.ingress.kubernetes.io/target-type: ip
    #     external-dns.alpha.kubernetes.io/hostname: weave-gitops.dallin.brewsentry.com
    #   hosts:
    #   - host: weave-gitops.dallin.brewsentry.com
    #     paths:
    #     - path: /
    #       pathType: Prefix
  interval: 60m0s
  releaseName: weave-gitops
  targetNamespace: weave-gitops
