{{ range $deployment, $values := .Values.deployments }}
{{- /* guarantees --- is on a newline */ -}}
{{ printf "\n---" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deployment }}
spec:
  replicas: {{ $values.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ $deployment }}
  template:
    metadata:
      labels:
        app: {{ $deployment }}
    spec:
      serviceAccountName: {{ $values.serviceAccountName }}
      containers:
      - name: {{ $deployment }}
        image: {{ $values.image }}
        env:
          - name: QUEUE
            value: {{ $values.queueName }}
{{ end }}
