deployments:

  sqs-producer:
    image: 704855531002.dkr.ecr.us-west-2.amazonaws.com/eks-fluxcd-lab-sqs-producer:latest
    serviceAccountName: sa-aws-sqs
    sqsQueueName: eks-fluxcd-lab-sqs-queue
    sleepWait: 10
    replicas: 1

  sqs-consumer:
    image: 704855531002.dkr.ecr.us-west-2.amazonaws.com/eks-fluxcd-lab-sqs-consumer:latest
    serviceAccountName: sa-aws-sqs
    sqsQueueName: eks-fluxcd-lab-sqs-queue
    sleepWait: 10
    replicas: 1
